In [1]:
import pandas as pd
import numpy as np
import otter
grader = otter.Notebook()

# <mark style="background: #801010; color: #ffffff;" >C</mark> Week 2: NumPy Arrays

------

### Instructions:

- Complete 50 points worth of questions to pass the assessment
  - You can attempt any number of questions and in any order provided you pass at least 50 points.
- These questions should be attempted directly in this notebook.
- Be sure to check your work before submitting.
  - Do not remove any provided markings from the answer spaces.
  - Do not make any changes to this notebook outside of the answer spaces provided.
  
#### Submitting

- Reset your outputs before submitting
  - Select the `Kernel` menu, then either `Restart & Run Clear Output` or `Restart & Run All`
  - Don't forget to save your notebook after this step
- Submit your .ipynb file to Gradescope using Git & GitHub
- You can submit as many times as needed
- When reviewing results, ignore any results listed under "Public Tests"  
  (There are no "Public Tests" in this assignment)

For more information, see the assessment page.

#### Question 01 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(1 Point)

Create a python program that has a 1-D array with 5 elements. It should contain the numbers 0 to 4 in sequence. Assign this array to `output1`.

In [3]:
import numpy as np
output1=np.arange(5)
output1
# Write your solution here


array([0, 1, 2, 3, 4])

#### Question 02 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(1 Point)

Create a python program that contains a 2-D array with 6 elements (2 rows and 3 columns) that represents the following array. Assign this array to `output2`.

$$\begin{bmatrix} 0 & 1 & 2 \\ 3 & 4 & 5 \end{bmatrix}$$

In [5]:
import numpy as np
output2=np.arange(0,6).reshape((2,3))
# Write your solution here
output2

array([[0, 1, 2],
       [3, 4, 5]])

#### Question 03 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(1 Point)
Create a python program that has a 2-D array with 6 elements (3 rows and 2 columns) that represents the following array. Assign this array to `output3`.

$$\begin{bmatrix} 0 & 1 \\ 2 & 3 \\ 4 & 5 \end{bmatrix}$$

In [8]:
import numpy as np


output3=np.arange(0,6).reshape(3,2)
# Write your solution here
output3

array([[0, 1],
       [2, 3],
       [4, 5]])

#### Question 04 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(1 Point)

Create a python program that has a 3-D array with 8 elements (2 rows and 2 columns, with a depth of 2) using the `zeros` function. Assign this array to `output4`.

In [11]:
import numpy as np
output4=np.zeros(8).reshape(2,2,2)
output4
# Write your solution here


array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

#### Question 05 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(2 Points)

You are given a 2-D array of unknown size named `array5`. Create a python program that finds the size of that array and returns the number of rows.

In [27]:
import numpy as np

def question05(array5):
    return array5.shape[0]
    
    

    # Write your solution here
question05(np.arange(6).reshape(2,3))

2

#### Question 06 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(2 Points)

Create a python program that performs the following calculation using universal functions. Assign the result to `output6`.

$$\begin{bmatrix} 0 & 1 \\ 2 & 3 \end{bmatrix} + \begin{bmatrix} 0 & 1 \\ 2 & 3 \end{bmatrix}$$

In [41]:
import numpy as np
a1=np.arange(0,4).reshape(2,2)
a2=np.arange(0,4).reshape(2,2)
def add_arr(a1,a2):
    return a1+a2
# Write your solution here
output6=add_arr(a1,a2)

#### Question 07 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(4 Points)
You are given two 2-D arrays of that are the same size (`array7_i` and `array7_ii`). Create a python program that multiplies the two arrays together using universal functions. Return a new array containing the result.

In [37]:
import numpy as np

def question07(array7_i,array7_ii):
    return np.multiply(array7_i,array7_ii)

    # Write your solution here



#### Question 08 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(4 Points)

Create a python program that performs the following calculation using universal functions. Assign the result to `output8`.

$$\begin{bmatrix} 0 & 1 \\ 2 & 3 \end{bmatrix} ** 3$$

In [47]:
import numpy as np

output8=np.arange(0,4).reshape(2,2)**3
output8
# Write your solution here


array([[ 0,  1],
       [ 8, 27]])

#### Question 09 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(4 Points)

Create a python program that has a 1-D array with 100 elements. It should contain the numbers 0, 2, 4, 6, all the way to 198 in sequence. Assign this array to `output9`.

In [ ]:
import numpy as np

# Write your solution here


#### Question 10 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(4 Points)

Create a python program that has a 1-D array with 16 elements. It should contain the numbers 10, 20, 30, 40, all the way to 160 in sequence. Afterwards, change its shape using `reshape` to a 4-D array. Assign this reshaped array to `output10`.

***
<details>
  <summary><span style="color:blue">Click to see Hints</span></summary>
   In one of the provided examples, you saw how a 2-D 3-by-3 array. Use that as a basis for reshaping into a 4-D 2-by-2-by-2-by-2 array. 
</details>

In [53]:
import numpy as np
output10=np.arange(10,161,10).reshape(2,2,2,2)
output10
# Write your solution here


array([[[[ 10,  20],
         [ 30,  40]],

        [[ 50,  60],
         [ 70,  80]]],


       [[[ 90, 100],
         [110, 120]],

        [[130, 140],
         [150, 160]]]])

###### Question 11 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(6 Points)

One of the most common models in statistics (and by extention data science) is the normal distribution. In order to graph a normal distribution first the mean and standard deviation of the data must be found. NumPy has functions that allow us to analyse data and obtain these values.

You are given an array of unknown size and dimensions named `array11` that represents some data. Create a python program that finds the both the mean and standard deviation (rounded to 4 decimal points) of the data. Return the values in a dictionary of the following structure:
```python
{
  "mean": some_value,
  "standard_deviation": some_value
}
```

In [61]:
import numpy as np

def question11(array11):
    dict_res={}
    dict_res['mean']=np.mean(array11)
    dict_res['standard_deviation']=np.std(array11)
    return dict_res

    # Write your solution here



#### Question 12 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(6 Points)

You are given an 1-D array of unknown size named `array12`. Create a python program that finds both the first element and the smallest element in the array. Return the values in a dictionary of the following structure:
```python
{
  "first": some_value,
  "smallest": some_value
}
```

In [74]:
import numpy as np

def question12(array12):
    dict_res={}
    dict_res['first']=array12[0]
    dict_res['smallest']=array12[0].min()
      
    return dict_res
    # Write your solution here



#### Question 13 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(6 Points)

You are given an 2-D array of unknown size named `array13`. Create a python program that finds the first row of data and the maximum number within that row.  Return the values in a dictionary of the following structure:
```python
{
  "first_row": some_value,
  "max_row_value": some_value
}
```

In [78]:
import numpy as np

def question13(array13):
    dict_res={}
    dict_res['first_row']=array13[0:1]
    dict_res['max_row_value']=array13[0:1].max()
    
    return(dict_res)
    

    # Write your solution here
question13(np.arange(0,4).reshape(2,2))

{'first_row': array([[0, 1]]), 'max_row_value': 1}

#### Question 14 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(6 Points)

You are given an 1-D array of unknown size named `array14`. Create a python program that finds the first 6 entries within that row. Next, split that array into two arrays using the `split` function. Return the values in a dictionary of the following structure:
```python
{
  "array": first_6_entries,
  "part1": split_first_half,
  "part2": split_other_half
}
```

In [95]:
import numpy as np

def question14(array14):
    v1,v2=np.split(array14,2)
    dict_Res={
  "array": array14[0:7],
  "part1":v1 ,
  "part2": v2
}
    return dict_Res
    # Write your solution here


In [94]:
v1 =np.array([1, 2, 3])
matrix = np.array([[4, 5, 6],[7, 8, 9]])
np.hsplit(matrix,3)

[array([[4],
        [7]]),
 array([[5],
        [8]]),
 array([[6],
        [9]])]

#### Question 15 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(6 Points)

You are given an 1-D array of 40 elements named `array15`. Create a python program that finds every second element starting from index 4 and stopping before index 20. Return the result.

In [96]:
import numpy as np

def question15(array15):
    return array15[4:20:2]
    # Write your solution here


#### Question 16 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(6 Points)

You are given 2 sorted 1-D arrays of 20 elements named `array16_i` and `array16_ii`. Create a python program that concatenates these two arrays by appending `array16_ii` to the end of `array16_i`. Afterwards, sort the new array.
Return both the unsorted concatenated array, and the sorted array in a dictionary of the following structure:
```python
{
  "concat": concatenated_array,
  "sorted": sorted_array
}
```

In [112]:
import numpy as np

def question16(array16_i, array16_ii):
    
    ret_dict={
  "concat": np.concatenate([array16_i,array16_ii]),
    
        
  "sorted": np.sort([(np.concatenate([array16_i,array16_ii]))])
}
    return ret_dict

    # Write your solution here


#### Question 17 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(8 Points)

Create a python program that:

1. initializes two arrays using the `arange` function followed by the `reshape` functions.
   1. The first array should have 2 rows and 5 columns and contain the numbers 0, 1, 2, up to and including 9.
   2. The second array should  have 2 rows and 3 columns and contain the numbers 1, 3, 5, up to and including 11.
2. concatenates these two arrays by appending along the column axis (creating an array with 2 rows and 8 columns), then transposes the result (creating an array with 8 rows and 2 columns).

Assign the end result to `output17`.

In [121]:
# Write your solution here
a1=np.arange(10).reshape(2,5)
a2=np.arange(1,12,2).reshape(2,3)
output17=np.concatenate([a1,a2],axis=1)
output17=np.transpose([output17])
output17.shape



(8, 2, 1)

#### Question 18 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(8 Points)

Create a python program that:

1. initializes two arrays using the `arange` function followed by the `reshape` functions.
   1. The first array should have 4 rows and 2 columns and contain the numbers 0, 1, 2, up to 7.
   2. The second array should have 3 rows and 2 columns and contain the numbers 0, 5, 10, up to 11.
2. concatenates these two arrays by appending along the row axis.
3. afterwards, reshape the new array into a 1-D array and sort it in decending order.

Assign the end result to `output18`.

In [126]:
# Write your solution here
a1=np.arange(0,8).reshape(4,2)
a2=np.arange(0,12,5).reshape(3,2)
a2

ValueError: cannot reshape array of size 3 into shape (3,2)

#### Question 19 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(12 Points)

Create a python program that:

1. initializes two 2-D arrays as depicted below.
$$a1 = \begin{bmatrix} 70 & 51 & 89 \\ 42 & 15 & 8 \end{bmatrix}, a2 = \begin{bmatrix} 75 & 12 & 38 \\ 99 & 75 & 45 \end{bmatrix}$$
2. performs integer division, by dividing the elements of a1 by a2. Assign this result to `output19_i`.
3. sums the three arrays together. Assign this result to `output19_ii`, also assign a copy of the second row to `output19_iii`.


In [151]:
# Write your solution here
a1=np.array([70,51,89,42,15,8])
a2=np.array([75,12,38,99,75,45])

a1=a1.reshape(2,3)
a2=a2.reshape(2,3)

output19_i=np.divide(a1,a2)
output19_i
output19_ii=a1+a2+output19_i
output19_iii=output19_ii[:1,:]


#### Question 20 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(12 Points)

Create a python program that:

1. initializes two 2-D arrays as depicted below.
$$a1 = \begin{bmatrix} 48 & 75 & 75 \\ 15 & 2 & 46 \end{bmatrix}, a2 = \begin{bmatrix} 78 & 15 & 87 \\ 0 & 61 & 9 \end{bmatrix}$$
2. multiplies the two arrays together, then slice the result to only assign the last column to `output20` (note: an n-row, 1-column array automatically converts into a 1-row, n-column array, leave your answer like this).


In [162]:
# Write your solution here
a1=np.array([48,75,75,15,2,46]).reshape(2,3)
a2=np.array([78,15,87,0,61,9]).reshape(2,3)
output20=a1*a2

output20=output20[:,2:3]
